### ISSUE TITLE
Failed to unmarshal salt, iv, and data values: unexpected end of JSON input

### ISSUE THREAD

**Issue by ducbot88** [cyclone-github/metamask_extractor#1]
Hi,

I'm getting new format, the result is like this:

{"data":"X4HGh4T2+cky7lC5p8nooeb2amGtDITGc+1e8+T3iTQqIZW40ymR7ZiqzKqqfTd6kG8/0D7PZC+XUkqV+dd","iv":"AJ+qL/K9HFGJo7OIE50HqA==","keyMetadata":{"algorithm":"PBKDF2","params":{"iterations":600000}
Failed to unmarshal salt, iv, and data values: unexpected end of JSON input

could you help to check this?

thank you.

**Comment by cyclone-github** [comment]
I'll be adding support for the new vault format (with dynamic iterations) soon.

**Comment by ducbot88** [comment]
Thank you, I'm waiting for the new version.
